builds:
  - id: darwin-amd64
    main: ./
    binary: chatgpt-tui
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: chatgpt-tui
    builds:
      - darwin-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  draft: false

brews:
  - name: chatgpt-tui
    homepage: https://github.com/tearingItUp786/chatgpt-tui
    tap:
      owner: tearingItUp786
      name: homebrew-tearingitup786
    commit_author:
      name: tearingitup786
